### ISSUE TITLE
[ERROR] aura token is empty on this shell "refresh-aws-session.sh"

### ISSUE THREAD

**Issue by anptgen** [lucendio/lecture-devops-code#1]
I get an error when executing the script [refresh-aws-session.sh] "[ERROR] aura token is empty"

**Comment by lucendio** [comment]
Unfortunately, I cannot reproduce this issue. Both account types (educator and student) work for me.

However, there was an error caused by a recent change introduced on the server side, which has been fixed: https://github.com/lucendio/lecture-devops-code/commit/524de2da3a2859772ae34c8849cf962100e6efde. You might wanna give it a try.

Feel free to run the script in [verbose mode](https://github.com/lucendio/lecture-devops-code/blob/524de2da3a2859772ae34c8849cf962100e6efde/hack/refresh-aws-session.sh#L8) and provide the files as well as the terminal output here, so we can have a look. BUT please be careful, this data may contain your login credentials.
